/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppFornecedoresRouteImport } from './routes/_app.fornecedores'
import { Route as AppFinanceiroRouteImport } from './routes/_app.financeiro'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppClientesRouteImport } from './routes/_app.clientes'
import { Route as AppProjetosIndexRouteImport } from './routes/_app.projetos.index'
import { Route as AppOrcamentosIndexRouteImport } from './routes/_app.orcamentos.index'
import { Route as AppFinanceiroIndexRouteImport } from './routes/_app.financeiro.index'
import { Route as AppContratosIndexRouteImport } from './routes/_app.contratos.index'
import { Route as AppProjetosNovoRouteImport } from './routes/_app.projetos.novo'
import { Route as AppProjetosIdRouteImport } from './routes/_app.projetos.$id'
import { Route as AppOrcamentosNovoRouteImport } from './routes/_app.orcamentos.novo'
import { Route as AppOrcamentosIdRouteImport } from './routes/_app.orcamentos.$id'
import { Route as AppFornecedoresNovoRouteImport } from './routes/_app.fornecedores.novo'
import { Route as AppFinanceiroReceberRouteImport } from './routes/_app.financeiro.receber'
import { Route as AppFinanceiroPagarRouteImport } from './routes/_app.financeiro.pagar'
import { Route as AppFinanceiroInvestimentosRouteImport } from './routes/_app.financeiro.investimentos'
import { Route as AppFinanceiroContasRouteImport } from './routes/_app.financeiro.contas'
import { Route as AppContratosNovoRouteImport } from './routes/_app.contratos.novo'
import { Route as AppContratosIdRouteImport } from './routes/_app.contratos.$id'
import { Route as AppClientesNovoRouteImport } from './routes/_app.clientes.novo'
import { Route as AppClientesIdRouteImport } from './routes/_app.clientes.$id'
import { Route as AppCadastrosProdutosRouteImport } from './routes/_app.cadastros.produtos'
import { Route as AppCadastrosCondicoesRouteImport } from './routes/_app.cadastros.condicoes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppFornecedoresRoute = AppFornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosIndexRoute = AppProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentosIndexRoute = AppOrcamentosIndexRouteImport.update({
  id: '/orcamentos/',
  path: '/orcamentos/',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroIndexRoute = AppFinanceiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppContratosIndexRoute = AppContratosIndexRouteImport.update({
  id: '/contratos/',
  path: '/contratos/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosNovoRoute = AppProjetosNovoRouteImport.update({
  id: '/projetos/novo',
  path: '/projetos/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosIdRoute = AppProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentosNovoRoute = AppOrcamentosNovoRouteImport.update({
  id: '/orcamentos/novo',
  path: '/orcamentos/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentosIdRoute = AppOrcamentosIdRouteImport.update({
  id: '/orcamentos/$id',
  path: '/orcamentos/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppFornecedoresNovoRoute = AppFornecedoresNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppFornecedoresRoute,
} as any)
const AppFinanceiroReceberRoute = AppFinanceiroReceberRouteImport.update({
  id: '/receber',
  path: '/receber',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroPagarRoute = AppFinanceiroPagarRouteImport.update({
  id: '/pagar',
  path: '/pagar',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroInvestimentosRoute =
  AppFinanceiroInvestimentosRouteImport.update({
    id: '/investimentos',
    path: '/investimentos',
    getParentRoute: () => AppFinanceiroRoute,
  } as any)
const AppFinanceiroContasRoute = AppFinanceiroContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppContratosNovoRoute = AppContratosNovoRouteImport.update({
  id: '/contratos/novo',
  path: '/contratos/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosIdRoute = AppContratosIdRouteImport.update({
  id: '/contratos/$id',
  path: '/contratos/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesNovoRoute = AppClientesNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppClientesRoute,
} as any)
const AppClientesIdRoute = AppClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppClientesRoute,
} as any)
const AppCadastrosProdutosRoute = AppCadastrosProdutosRouteImport.update({
  id: '/cadastros/produtos',
  path: '/cadastros/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosCondicoesRoute = AppCadastrosCondicoesRouteImport.update({
  id: '/cadastros/condicoes',
  path: '/cadastros/condicoes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/clientes': typeof AppClientesRouteWithChildren
  '/configuracoes': typeof AppConfiguracoesRoute
  '/financeiro': typeof AppFinanceiroRouteWithChildren
  '/fornecedores': typeof AppFornecedoresRouteWithChildren
  '/cadastros/condicoes': typeof AppCadastrosCondicoesRoute
  '/cadastros/produtos': typeof AppCadastrosProdutosRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/clientes/novo': typeof AppClientesNovoRoute
  '/contratos/$id': typeof AppContratosIdRoute
  '/contratos/novo': typeof AppContratosNovoRoute
  '/financeiro/contas': typeof AppFinanceiroContasRoute
  '/financeiro/investimentos': typeof AppFinanceiroInvestimentosRoute
  '/financeiro/pagar': typeof AppFinanceiroPagarRoute
  '/financeiro/receber': typeof AppFinanceiroReceberRoute
  '/fornecedores/novo': typeof AppFornecedoresNovoRoute
  '/orcamentos/$id': typeof AppOrcamentosIdRoute
  '/orcamentos/novo': typeof AppOrcamentosNovoRoute
  '/projetos/$id': typeof AppProjetosIdRoute
  '/projetos/novo': typeof AppProjetosNovoRoute
  '/contratos/': typeof AppContratosIndexRoute
  '/financeiro/': typeof AppFinanceiroIndexRoute
  '/orcamentos/': typeof AppOrcamentosIndexRoute
  '/projetos/': typeof AppProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/clientes': typeof AppClientesRouteWithChildren
  '/configuracoes': typeof AppConfiguracoesRoute
  '/fornecedores': typeof AppFornecedoresRouteWithChildren
  '/': typeof AppIndexRoute
  '/cadastros/condicoes': typeof AppCadastrosCondicoesRoute
  '/cadastros/produtos': typeof AppCadastrosProdutosRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/clientes/novo': typeof AppClientesNovoRoute
  '/contratos/$id': typeof AppContratosIdRoute
  '/contratos/novo': typeof AppContratosNovoRoute
  '/financeiro/contas': typeof AppFinanceiroContasRoute
  '/financeiro/investimentos': typeof AppFinanceiroInvestimentosRoute
  '/financeiro/pagar': typeof AppFinanceiroPagarRoute
  '/financeiro/receber': typeof AppFinanceiroReceberRoute
  '/fornecedores/novo': typeof AppFornecedoresNovoRoute
  '/orcamentos/$id': typeof AppOrcamentosIdRoute
  '/orcamentos/novo': typeof AppOrcamentosNovoRoute
  '/projetos/$id': typeof AppProjetosIdRoute
  '/projetos/novo': typeof AppProjetosNovoRoute
  '/contratos': typeof AppContratosIndexRoute
  '/financeiro': typeof AppFinanceiroIndexRoute
  '/orcamentos': typeof AppOrcamentosIndexRoute
  '/projetos': typeof AppProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/clientes': typeof AppClientesRouteWithChildren
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/financeiro': typeof AppFinanceiroRouteWithChildren
  '/_app/fornecedores': typeof AppFornecedoresRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/cadastros/condicoes': typeof AppCadastrosCondicoesRoute
  '/_app/cadastros/produtos': typeof AppCadastrosProdutosRoute
  '/_app/clientes/$id': typeof AppClientesIdRoute
  '/_app/clientes/novo': typeof AppClientesNovoRoute
  '/_app/contratos/$id': typeof AppContratosIdRoute
  '/_app/contratos/novo': typeof AppContratosNovoRoute
  '/_app/financeiro/contas': typeof AppFinanceiroContasRoute
  '/_app/financeiro/investimentos': typeof AppFinanceiroInvestimentosRoute
  '/_app/financeiro/pagar': typeof AppFinanceiroPagarRoute
  '/_app/financeiro/receber': typeof AppFinanceiroReceberRoute
  '/_app/fornecedores/novo': typeof AppFornecedoresNovoRoute
  '/_app/orcamentos/$id': typeof AppOrcamentosIdRoute
  '/_app/orcamentos/novo': typeof AppOrcamentosNovoRoute
  '/_app/projetos/$id': typeof AppProjetosIdRoute
  '/_app/projetos/novo': typeof AppProjetosNovoRoute
  '/_app/contratos/': typeof AppContratosIndexRoute
  '/_app/financeiro/': typeof AppFinanceiroIndexRoute
  '/_app/orcamentos/': typeof AppOrcamentosIndexRoute
  '/_app/projetos/': typeof AppProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/clientes'
    | '/configuracoes'
    | '/financeiro'
    | '/fornecedores'
    | '/cadastros/condicoes'
    | '/cadastros/produtos'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/contratos/$id'
    | '/contratos/novo'
    | '/financeiro/contas'
    | '/financeiro/investimentos'
    | '/financeiro/pagar'
    | '/financeiro/receber'
    | '/fornecedores/novo'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/contratos/'
    | '/financeiro/'
    | '/orcamentos/'
    | '/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/clientes'
    | '/configuracoes'
    | '/fornecedores'
    | '/'
    | '/cadastros/condicoes'
    | '/cadastros/produtos'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/contratos/$id'
    | '/contratos/novo'
    | '/financeiro/contas'
    | '/financeiro/investimentos'
    | '/financeiro/pagar'
    | '/financeiro/receber'
    | '/fornecedores/novo'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/contratos'
    | '/financeiro'
    | '/orcamentos'
    | '/projetos'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/clientes'
    | '/_app/configuracoes'
    | '/_app/financeiro'
    | '/_app/fornecedores'
    | '/_app/'
    | '/_app/cadastros/condicoes'
    | '/_app/cadastros/produtos'
    | '/_app/clientes/$id'
    | '/_app/clientes/novo'
    | '/_app/contratos/$id'
    | '/_app/contratos/novo'
    | '/_app/financeiro/contas'
    | '/_app/financeiro/investimentos'
    | '/_app/financeiro/pagar'
    | '/_app/financeiro/receber'
    | '/_app/fornecedores/novo'
    | '/_app/orcamentos/$id'
    | '/_app/orcamentos/novo'
    | '/_app/projetos/$id'
    | '/_app/projetos/novo'
    | '/_app/contratos/'
    | '/_app/financeiro/'
    | '/_app/orcamentos/'
    | '/_app/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fornecedores': {
      id: '/_app/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AppFornecedoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projetos/': {
      id: '/_app/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof AppProjetosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamentos/': {
      id: '/_app/orcamentos/'
      path: '/orcamentos'
      fullPath: '/orcamentos/'
      preLoaderRoute: typeof AppOrcamentosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro/': {
      id: '/_app/financeiro/'
      path: '/'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof AppFinanceiroIndexRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/contratos/': {
      id: '/_app/contratos/'
      path: '/contratos'
      fullPath: '/contratos/'
      preLoaderRoute: typeof AppContratosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projetos/novo': {
      id: '/_app/projetos/novo'
      path: '/projetos/novo'
      fullPath: '/projetos/novo'
      preLoaderRoute: typeof AppProjetosNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projetos/$id': {
      id: '/_app/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof AppProjetosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamentos/novo': {
      id: '/_app/orcamentos/novo'
      path: '/orcamentos/novo'
      fullPath: '/orcamentos/novo'
      preLoaderRoute: typeof AppOrcamentosNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamentos/$id': {
      id: '/_app/orcamentos/$id'
      path: '/orcamentos/$id'
      fullPath: '/orcamentos/$id'
      preLoaderRoute: typeof AppOrcamentosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fornecedores/novo': {
      id: '/_app/fornecedores/novo'
      path: '/novo'
      fullPath: '/fornecedores/novo'
      preLoaderRoute: typeof AppFornecedoresNovoRouteImport
      parentRoute: typeof AppFornecedoresRoute
    }
    '/_app/financeiro/receber': {
      id: '/_app/financeiro/receber'
      path: '/receber'
      fullPath: '/financeiro/receber'
      preLoaderRoute: typeof AppFinanceiroReceberRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/pagar': {
      id: '/_app/financeiro/pagar'
      path: '/pagar'
      fullPath: '/financeiro/pagar'
      preLoaderRoute: typeof AppFinanceiroPagarRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/investimentos': {
      id: '/_app/financeiro/investimentos'
      path: '/investimentos'
      fullPath: '/financeiro/investimentos'
      preLoaderRoute: typeof AppFinanceiroInvestimentosRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/financeiro/contas': {
      id: '/_app/financeiro/contas'
      path: '/contas'
      fullPath: '/financeiro/contas'
      preLoaderRoute: typeof AppFinanceiroContasRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/_app/contratos/novo': {
      id: '/_app/contratos/novo'
      path: '/contratos/novo'
      fullPath: '/contratos/novo'
      preLoaderRoute: typeof AppContratosNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contratos/$id': {
      id: '/_app/contratos/$id'
      path: '/contratos/$id'
      fullPath: '/contratos/$id'
      preLoaderRoute: typeof AppContratosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/novo': {
      id: '/_app/clientes/novo'
      path: '/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof AppClientesNovoRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/_app/clientes/$id': {
      id: '/_app/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AppClientesIdRouteImport
      parentRoute: typeof AppClientesRoute
    }
    '/_app/cadastros/produtos': {
      id: '/_app/cadastros/produtos'
      path: '/cadastros/produtos'
      fullPath: '/cadastros/produtos'
      preLoaderRoute: typeof AppCadastrosProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cadastros/condicoes': {
      id: '/_app/cadastros/condicoes'
      path: '/cadastros/condicoes'
      fullPath: '/cadastros/condicoes'
      preLoaderRoute: typeof AppCadastrosCondicoesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppClientesRouteChildren {
  AppClientesIdRoute: typeof AppClientesIdRoute
  AppClientesNovoRoute: typeof AppClientesNovoRoute
}

const AppClientesRouteChildren: AppClientesRouteChildren = {
  AppClientesIdRoute: AppClientesIdRoute,
  AppClientesNovoRoute: AppClientesNovoRoute,
}

const AppClientesRouteWithChildren = AppClientesRoute._addFileChildren(
  AppClientesRouteChildren,
)

interface AppFinanceiroRouteChildren {
  AppFinanceiroContasRoute: typeof AppFinanceiroContasRoute
  AppFinanceiroInvestimentosRoute: typeof AppFinanceiroInvestimentosRoute
  AppFinanceiroPagarRoute: typeof AppFinanceiroPagarRoute
  AppFinanceiroReceberRoute: typeof AppFinanceiroReceberRoute
  AppFinanceiroIndexRoute: typeof AppFinanceiroIndexRoute
}

const AppFinanceiroRouteChildren: AppFinanceiroRouteChildren = {
  AppFinanceiroContasRoute: AppFinanceiroContasRoute,
  AppFinanceiroInvestimentosRoute: AppFinanceiroInvestimentosRoute,
  AppFinanceiroPagarRoute: AppFinanceiroPagarRoute,
  AppFinanceiroReceberRoute: AppFinanceiroReceberRoute,
  AppFinanceiroIndexRoute: AppFinanceiroIndexRoute,
}

const AppFinanceiroRouteWithChildren = AppFinanceiroRoute._addFileChildren(
  AppFinanceiroRouteChildren,
)

interface AppFornecedoresRouteChildren {
  AppFornecedoresNovoRoute: typeof AppFornecedoresNovoRoute
}

const AppFornecedoresRouteChildren: AppFornecedoresRouteChildren = {
  AppFornecedoresNovoRoute: AppFornecedoresNovoRoute,
}

const AppFornecedoresRouteWithChildren = AppFornecedoresRoute._addFileChildren(
  AppFornecedoresRouteChildren,
)

interface AppRouteChildren {
  AppClientesRoute: typeof AppClientesRouteWithChildren
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppFinanceiroRoute: typeof AppFinanceiroRouteWithChildren
  AppFornecedoresRoute: typeof AppFornecedoresRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppCadastrosCondicoesRoute: typeof AppCadastrosCondicoesRoute
  AppCadastrosProdutosRoute: typeof AppCadastrosProdutosRoute
  AppContratosIdRoute: typeof AppContratosIdRoute
  AppContratosNovoRoute: typeof AppContratosNovoRoute
  AppOrcamentosIdRoute: typeof AppOrcamentosIdRoute
  AppOrcamentosNovoRoute: typeof AppOrcamentosNovoRoute
  AppProjetosIdRoute: typeof AppProjetosIdRoute
  AppProjetosNovoRoute: typeof AppProjetosNovoRoute
  AppContratosIndexRoute: typeof AppContratosIndexRoute
  AppOrcamentosIndexRoute: typeof AppOrcamentosIndexRoute
  AppProjetosIndexRoute: typeof AppProjetosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientesRoute: AppClientesRouteWithChildren,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppFinanceiroRoute: AppFinanceiroRouteWithChildren,
  AppFornecedoresRoute: AppFornecedoresRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppCadastrosCondicoesRoute: AppCadastrosCondicoesRoute,
  AppCadastrosProdutosRoute: AppCadastrosProdutosRoute,
  AppContratosIdRoute: AppContratosIdRoute,
  AppContratosNovoRoute: AppContratosNovoRoute,
  AppOrcamentosIdRoute: AppOrcamentosIdRoute,
  AppOrcamentosNovoRoute: AppOrcamentosNovoRoute,
  AppProjetosIdRoute: AppProjetosIdRoute,
  AppProjetosNovoRoute: AppProjetosNovoRoute,
  AppContratosIndexRoute: AppContratosIndexRoute,
  AppOrcamentosIndexRoute: AppOrcamentosIndexRoute,
  AppProjetosIndexRoute: AppProjetosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
